/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiImageSearchRouteImport } from './routes/api/image-search'
import { Route as ApiImageProxyRouteImport } from './routes/api/image-proxy'
import { Route as ApiImagesEntryIdRouteImport } from './routes/api/images/$entryId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiImageSearchRoute = ApiImageSearchRouteImport.update({
  id: '/api/image-search',
  path: '/api/image-search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiImageProxyRoute = ApiImageProxyRouteImport.update({
  id: '/api/image-proxy',
  path: '/api/image-proxy',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiImagesEntryIdRoute = ApiImagesEntryIdRouteImport.update({
  id: '/api/images/$entryId',
  path: '/api/images/$entryId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/image-proxy': typeof ApiImageProxyRoute
  '/api/image-search': typeof ApiImageSearchRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/images/$entryId': typeof ApiImagesEntryIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/image-proxy': typeof ApiImageProxyRoute
  '/api/image-search': typeof ApiImageSearchRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/images/$entryId': typeof ApiImagesEntryIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/image-proxy': typeof ApiImageProxyRoute
  '/api/image-search': typeof ApiImageSearchRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/images/$entryId': typeof ApiImagesEntryIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/image-proxy'
    | '/api/image-search'
    | '/api/auth/$'
    | '/api/images/$entryId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/image-proxy'
    | '/api/image-search'
    | '/api/auth/$'
    | '/api/images/$entryId'
  id:
    | '__root__'
    | '/'
    | '/api/image-proxy'
    | '/api/image-search'
    | '/api/auth/$'
    | '/api/images/$entryId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiImageProxyRoute: typeof ApiImageProxyRoute
  ApiImageSearchRoute: typeof ApiImageSearchRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiImagesEntryIdRoute: typeof ApiImagesEntryIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/image-search': {
      id: '/api/image-search'
      path: '/api/image-search'
      fullPath: '/api/image-search'
      preLoaderRoute: typeof ApiImageSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/image-proxy': {
      id: '/api/image-proxy'
      path: '/api/image-proxy'
      fullPath: '/api/image-proxy'
      preLoaderRoute: typeof ApiImageProxyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/images/$entryId': {
      id: '/api/images/$entryId'
      path: '/api/images/$entryId'
      fullPath: '/api/images/$entryId'
      preLoaderRoute: typeof ApiImagesEntryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiImageProxyRoute: ApiImageProxyRoute,
  ApiImageSearchRoute: ApiImageSearchRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiImagesEntryIdRoute: ApiImagesEntryIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
